language: python

sudo: false

cache: pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3

install:
  - pip install pip setuptools --upgrade
  - pip install -e .\[all\]

script:
  - pytest tests --cov pcalc --cov-report term-missing

after_success:
  - bash <(curl -s https://codecov.io/bash)
